/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Rec();
export const Hospital = IDL.Record({
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'location' : IDL.Text,
});
Question.fill(
  IDL.Record({
    'text' : IDL.Text,
    'nextQuestions' : IDL.Vec(Question),
    'options' : IDL.Vec(IDL.Text),
  })
);

export const idlService = IDL.Service({
  'addHospital' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'findHospitalByName' : IDL.Func([IDL.Text], [IDL.Opt(Hospital)], ['query']),
  'findHospitalsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Hospital)],
      ['query'],
    ),
  'findHospitalsBySpecialty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Hospital)],
      ['query'],
    ),
  'getInitialQuestion' : IDL.Func([], [Question], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Rec();
  const Hospital = IDL.Record({
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'location' : IDL.Text,
  });
  Question.fill(
    IDL.Record({
      'text' : IDL.Text,
      'nextQuestions' : IDL.Vec(Question),
      'options' : IDL.Vec(IDL.Text),
    })
  );
  
  return IDL.Service({
    'addHospital' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'findHospitalByName' : IDL.Func([IDL.Text], [IDL.Opt(Hospital)], ['query']),
    'findHospitalsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Hospital)],
        ['query'],
      ),
    'findHospitalsBySpecialty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Hospital)],
        ['query'],
      ),
    'getInitialQuestion' : IDL.Func([], [Question], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };