/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Hospital {
  'name' : string,
  'specialty' : string,
  'location' : string,
}
export interface Question {
  'text' : string,
  'nextQuestions' : Array<Question>,
  'options' : Array<string>,
}
export interface _SERVICE {
  'addHospital' : ActorMethod<[string, string, string], undefined>,
  'findHospitalByName' : ActorMethod<[string], [] | [Hospital]>,
  'findHospitalsByLocation' : ActorMethod<[string], Array<Hospital>>,
  'findHospitalsBySpecialty' : ActorMethod<[string], Array<Hospital>>,
  'getInitialQuestion' : ActorMethod<[], Question>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];